### ISSUE TITLE
IntelliJ doesn't install

### ISSUE THREAD

**Issue by gragera** [boxen/puppet-intellij#5]
Hi,

I'm trying to use this module to install IntelliJ community edition but it doesn't seem to do anything. We're integrating it in a boxen project file and the code there looks like this:

class projects::androidapp {

  ...
  class { 'intellij':
    edition => 'community',
  }  

  ...

}

And in the Puppetfile

...
github "intellij",      "1.3.0"

There is nothing in the output and the program is not installed. Please let me know if you need any other information or trace (I'm not hugely familiar with puppet really)

Thanks!

**Comment by leeyoda** [comment]
It won't install for me no matter what. And I tried every combination possible for the class thing and the tag. Always giving me the following error:

Error: Execution of '/usr/bin/hdiutil mount -plist -nobrowse -readonly -mountrandom /tmp /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/d20150115-6265-12kqooq/IntelliJ-IDEA-IC-12.1.2' returned 1: hdiutil: mount failed - image not recognized
Error: /Stage[main]/Intellij/Package[IntelliJ-IDEA-IC-12.1.2]/ensure: change from absent to present failed: Execution of '/usr/bin/hdiutil mount -plist -nobrowse -readonly -mountrandom /tmp /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/d20150115-6265-12kqooq/IntelliJ-IDEA-IC-12.1.2' returned 1: hdiutil: mount failed - image not recognized

**Comment by jacobbednarz** [comment]
Deprecated in favour of [brewcask][1] and [Boxen's in built support for
homebrew/brewcask][2].

[1]: https://caskroom.github.io/
[2]: https://github.com/boxen/puppet-boxen/blob/master/manifests/personal.pp#L14-L17
