### ISSUE TITLE
Gives the following error and doesn't install

### ISSUE THREAD

**Issue by leeyoda** [boxen/puppet-intellij#9]
Hi 

I am trying to get intellij installed, but failed to due to the following errors.
Error: Execution of '/usr/bin/hdiutil convert /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/d20150115-11653-keqqa3/IntelliJ-IDEA-IU-13.1.3 -format UDTO -o /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/d20150115-11653-keqqa3/appdmg_eula' returned 1: hdiutil: convert failed - image not recognized
Error: /Stage[main]/Intellij/Package[IntelliJ-IDEA-IU-13.1.3]/ensure: change from absent to present failed: Execution of '/usr/bin/hdiutil convert /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/d20150115-11653-keqqa3/IntelliJ-IDEA-IU-13.1.3 -format UDTO -o /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/d20150115-11653-keqqa3/appdmg_eula' returned 1: hdiutil: convert failed - image not recognized

I tried:
  class { 'intellij':
    edition => 'ultimate',
    version => '13.1.3'
  }
with 
github "intellij", "1.5.1"

or any other possible combinations such as community with various versions.

Please help since it is blocking me. :(

**Comment by sralmai** [comment]
Also seen on a fresh OSX 10.10.1 box with v1.5.1.

**Comment by samsonnguyen** [comment]
This is a duplicate issue of https://github.com/boxen/puppet-intellij/issues/5

**Comment by greglu** [comment]
In case anyone has a similar issue with the latest version (15.0) of IntelliJ, I've been able to resolve this by specifying the version like so:

```
class { 'intellij':
  edition => 'community',
  version => '15.0-custom-jdk-bundled'
}
```

**Comment by jacobbednarz** [comment]
Deprecated in favour of [brewcask][1] and [Boxen's in built support for
homebrew/brewcask][2].

[1]: https://caskroom.github.io/
[2]: https://github.com/boxen/puppet-boxen/blob/master/manifests/personal.pp#L14-L17
